### ISSUE TITLE
Upload Media method fails with parser error

### ISSUE THREAD

**Issue by gilmae** [tootsuite/mastodon-api#40]
When using the REST::Client#upload_media method the gem fails with the following error:

> /usr/local/lib/ruby/gems/2.4.0/gems/http-2.2.2/lib/http/mime_type.rb:37:in `[]': Unknown MIME type: text/html (HTTP::Error)
> 	from /usr/local/lib/ruby/gems/2.4.0/gems/http-2.2.2/lib/http/response.rb:141:in `parse'
> 	from /usr/local/lib/ruby/gems/2.4.0/gems/mastodon-api-1.1.0/lib/mastodon/rest/request.rb:22:in `perform'
> 	from /usr/local/lib/ruby/gems/2.4.0/gems/mastodon-api-1.1.0/lib/mastodon/rest/utils.rb:10:in `perform_request'
> 	from /usr/local/lib/ruby/gems/2.4.0/gems/mastodon-api-1.1.0/lib/mastodon/rest/utils.rb:18:in `perform_request_with_object'
> 	from /usr/local/lib/ruby/gems/2.4.0/gems/mastodon-api-1.1.0/lib/mastodon/rest/media.rb:13:in `upload_media'

Using `curl` to post media to the API is fine; experimentation revealed that when the POST is made without `multipart/form-data` then a HTML error page is displayed. Specifically:

`curl -d "file=@/tmp/5c4c20bb27ebf_IMG_0067.jpg"  -H "Authorization: Bearer [[DELETED]]" https://mastodon.social/api/v1/media`

Results in:

```
<!DOCTYPE html>
<html lang='en'>
<head>
<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
<meta charset='utf-8'>
<title>This page is not correct
 - Mastodon</title>
<meta content='width=device-width,initial-scale=1' name='viewport'>
<link rel="stylesheet" media="all" href="/packs/common-98f30779f214ab4fc61f.css" />
<link rel="stylesheet" media="all" href="/packs/default-1f373ed7152936ab8212.css" />
</head>
<body class='error'>
<div class='dialog'>
<img alt='Mastodon' src='/oops.gif'>
<div>
<h1>We&#39;re sorry, but something went wrong on our end.
</h1>
</div>
</div>
</body>
</html>
```

A valid POST returns JSON, and the error mentions being unable to parse text/html. Two and two are being put together at this point.

Using tcpflow to spy upon the request (albeit to http://mastodon.socal rather than https) suggests the mastodon-api gem is not using multipart/form-data to post the media:

```
POST /api/v1/media HTTP/1.1
User-Agent: MastodonRubyGem/1.1.0
Accept: */*
Authorization: Bearer [[DELETED]]
Connection: close
Content-Type: application/x-www-form-urlencoded
Content-Length: 39
Host: mastodon.social

file=%23%3CFile%3A0x00007ff27bc14510%3E
136.243.102.156.00080-192.168.020.032.57812: HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.3 (Ubuntu)
Date: Sun, 27 Jan 2019 08:43:06 GMT
Content-Type: text/html
Content-Length: 194
Connection: close
Location: https://mastodon.social/api/v1/media

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

Note the content type header: **Content-Type: application/x-www-form-urlencoded**

It is not beyond the realms of possibility that the content type is incorrect because I used http instead of https, but for the sake of experimentation, I will assume that this is not the case.

**Comment by gilmae** [comment]
Closed.

a) I was passing a ruby File class, not HTTP::FormData::File
b) I assume the code in master was an accurate representation of the gem and that the File would be converted. It was not.
