### ISSUE TITLE
Error calling create_status: undefined method `to_h' for []:Array (NoMethodError)

### ISSUE THREAD

**Issue by ryanfb** [tootsuite/mastodon-api#8]
After getting a token with write scope and initializing a client instance, trying `client.create_status('test')` results in the following exception:

```
mastodon-api-1.1.0/lib/mastodon/rest/utils.rb:36:in `array_param': undefined method `to_h' for []:Array (NoMethodError)
mastodon-api-1.1.0/lib/mastodon/rest/statuses.rb:15:in `create_status'
```

**Comment by ryanfb** [comment]
Closing this issue as I think it was a problem with my access token.
